export const CHANGE_SEARCH_PARAM = 'CHANGE_SEARCH_PARAM';
export const START_LOADING_AUCTIONS = 'START_LOADING_AUCTIONS';
export const FINISH_LOADING_AUCTIONS = 'FINISH_LOADING_AUCTIONS';

export const START_LOADING_DETAILS = 'START_LOADING_DETAILS';
export const FINISH_LOADING_DETAILS = 'FINISH_LOADING_DETAILS';
