export const GET_AUCTIONS_REQUEST = 'GET_AUCTIONS_REQUEST';
export const GET_AUCTIONS_SUCCESS = 'GET_AUCTIONS_SUCCESS';
export const GET_AUCTIONS_FAILED = 'GET_AUCTIONS_FAILED';
export const UPDATE_AUCTIONS_SUCCESS = 'UPDATE_AUCTIONS_SUCCESS';
export const UPDATE_AUCTIONS_FAILED = 'UPDATE_AUCTIONS_FAILED';
export const SET_FILTER = 'SET_FILTER';
